# Generated by Django 2.0.7 on 2018-08-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='s3Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3Url', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='is_s3_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='s3Images',
            field=models.ManyToManyField(to='events.s3Images'),
        ),
    ]
