# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
        ('events', '0002_auto_20180809_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name=b's3Images',
        ),
        migrations.AddField(
            model_name='s3images',
            name='athlete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='athletes.Athlete'),
        ),
        migrations.AddField(
            model_name='s3images',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Event'),
        ),
    ]
