# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180813_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(default=b'Not Processed', max_length=30, null=True),
        ),
    ]
