# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180813_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(default=b'NotProcessed', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='s3images',
            name='athlete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='athletes.Athlete'),
        ),
        migrations.AlterField(
            model_name='s3images',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
