# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_auto_20180912_1048'),
        ('events', '0010_scanlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s3images',
            name='athlete',
        ),
        migrations.AddField(
            model_name='s3images',
            name='athlete',
            field=models.ManyToManyField(to='athletes.Athlete'),
        ),
    ]
