# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-26 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20180927_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dbx_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='threshold',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
