# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-01 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
                ('dbx_path', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='image_links',
            field=models.ManyToManyField(to='events.EventImage'),
        ),
    ]
