# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-01 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0004_athlete_user'),
        ('events', '0014_auto_20190101_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='athlete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='athletes.Athlete'),
        ),
    ]
