# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-20 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='time_of_completion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
