# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-20 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0007_auto_20190212_1231'),
        ('events', '0019_scanlog_time_of_completion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_link', models.CharField(max_length=200)),
                ('is_person_found', models.BooleanField(default=False)),
                ('comment', models.TextField(max_length=200, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.Athlete')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
