# Generated by Django 2.0.7 on 2018-08-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20180801_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fb_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
