# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-12 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='s3ImageUrl',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
