# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-12 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_athlete_s3imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name=b'Athletes/Images'),
        ),
    ]
