# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-13 13:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('athletes', '0003_auto_20180912_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
