# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-08 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0004_athlete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='is_provider',
            field=models.BooleanField(default=False),
        ),
    ]
